project:
  type: website

website:
  title: "Breathing in Mexico City"
  navbar:
    left:
      - href: index.qmd
        text: "The Article"
      - href: methodology.qmd
        text: "Technical Appendix"

format:
  html:
    theme: cosmo
    toc: true